channels:
- conda-forge
dependencies:
- numpy =1.26.3
- openjdk
- owlready2 =0.45
- pandas =2.1.4
- pint =0.23
- python >= 3.8
- mp-api >= 0.39.4
- pyiron_atomistics >= 0.4.4
- pyiron-data >= 0.0.27
- lammps
