channels:
- conda-forge
dependencies:
- numpy =1.26.4
- openjdk
- owlready2 =0.47
- pandas =2.2.3
- pint =0.24.4
- semantikon =0.0.16
- pyiron_workflow =0.13.0
- rdflib =7.1.1
- owlrl =7.1.2
- pyiron_atomistics =0.6.19
- pyiron-data =0.0.30
- lammps =2024.02.07=*_openmpi_*
