channels:
- conda-forge
dependencies:
- numpy =2.2.6
- openjdk
- owlready2 =0.48
- pandas =2.2.3
- pint =0.24.4
- semantikon =0.0.21
- pyiron_workflow =0.13.3
- rdflib =7.1.4
- owlrl =7.1.2
- pyiron_atomistics =0.6.19
- pyiron-data =0.0.30
- lammps =2024.02.07=*_openmpi_*
