channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- numpy =1.26.4
- openjdk
- owlready2 =0.48
- pandas =2.3.2
- pint =0.24.4
- semantikon =0.0.21
- pyiron_workflow =0.13.3
- rdflib =7.1.4
- owlrl =7.1.2
- sphinxcontrib-mermaid
