channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- numpy =2.0.2
- openjdk
- owlready2 =0.47
- pandas =2.2.3
- pint =0.24.4
- semantikon =0.0.12
- pyiron_workflow =0.12.0
- rdflib =7.1.1
- owlrl =7.1.2
- sphinxcontrib-mermaid
