channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- numpy =1.26.4
- openjdk
- owlready2 =0.47
- pandas =2.2.3
- pint =0.24.4
- semantikon =0.0.6
- pyiron_workflow =0.11.2
- sphinxcontrib-mermaid
