channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- numpy =1.26.4
- openjdk
- owlready2 =0.47
- pandas =2.2.2
- pint =0.23
- sphinxcontrib-mermaid
