# This runs cron jobs daily

name: Daily

on:
  schedule:
    - cron: '00 23 * * *'

jobs:
  Tests-and-Coverage:
    uses: pyiron/actions/.github/workflows/tests-and-coverage.yml@actions-2.0.2
    secrets: inherit
    with:
      tests-env-files: .ci_support/environment.yml .ci_support/environment-pyiron_atomistics.yml
