# This runs cron jobs daily

name: Daily

on:
  schedule:
    - cron: '00 23 * * *'

jobs:
  Tests-and-Coverage:
    uses: pyiron/actions/.github/workflows/tests-and-coverage.yml@main
    secrets: inherit
