name: UpdateDependabotPR

on:
  pull_request_target:
    branches: [ main ]

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/dependabot-pr.yml@update_used_action_versions
    secrets: inherit