# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-Pull

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    runs-on: ubuntu-latest
    uses: pyiron/actions/cached-miniforge@update_env_setup
    with:
      runner-name: ${{ runner.name }}
      python-version: '3.11'