# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-Pull-main

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/push-pull-main.yml@main
    secrets: inherit
    with:
      docs-env-files: .ci_support/environment.yml .ci_support/environment-docs.yml
      notebooks-env-files: .ci_support/environment.yml .ci_support/environment-pyiron_atomistics.yml .ci_support/environment-lammps.yml
      tests-env-files: .ci_support/environment.yml .ci_support/environment-pyiron_atomistics.yml