# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-Pull

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pyiron/actions/cached-miniforge@update_env_setup
        with:
          python-version: '3.11'