# Take == dependencies in pyproject.toml (or equivalent) and relax them
# according to conda environment yaml files and rules for semantic versioning,
# then make a pypi release.
# For full docs cf. .support/update_pyproject_dependencies.py'
# Usage:
#   on:
#     release:
#       types: [published]

name: Pyproject Release

on:
  pull_request:


jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/pyproject-release.yml@debug_release
    secrets: inherit
    with:
      semantic-upper-bound: 'minor'
      lower-bound-yaml: '.ci_support/lower_bound.yml'