# This runs jobs which pyiron modules should run on release
name: Release

on:
  release:
    types: [ published ]

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/pyproject-release.yml@update_used_action_versions
    secrets: inherit
    with:
      semantic-upper-bound: 'minor'
      lower-bound-yaml: '.ci_support/lower_bound.yml'