# This runs cron jobs weekly

name: Weekly

on:
  schedule:
    - cron: '0 23 * * 2'

jobs:
  codeql:
    uses: pyiron/actions/.github/workflows/codeql.yml@update_used_action_versions
    secrets: inherit